### ISSUE TITLE
Better Refresh option

### ISSUE THREAD

**Issue by rdooley** [mpavan/ediblepickle#2]
It would be nice if the refresh parameter in the checkpoint decorator were able to read from the function being decorated parameters, say defaulting to False if refresh isn't in the kwargs of the function.

**Comment by mpavan** [comment]
Thanks for the suggestion.

I avoided overlapping function arguments with checkpoints to avoid people having to redesign their functions (every checkpointed function then needs to add either **kwargs or a specially designed checkpoint keyword).

It is currently fixed with a little difficulty on the user's side: by combining mutable objects and lambda. Here is an illustration:

This is a variable that lets us control the refreshing of a checkpoint:

```
#defs.py:
REFRESH = [0] # Needs to be a mutable object.
```

The checkpoint needs to use both lambda and the mutable REFRESH object.

```
# module.py
from ediblepickle import checkpoint
from defs import REFRESH
from time import sleep
@checkpoint('/tmp/test.obj',refresh=lambda:REFRESH[0])
def myfunc():
    sleep(2)
    return range(10)
```

Now, main.py accesses the mutable object and resets it:

```
# main.py
from defs import REFRESH
from module import myfunc

REFRESH[0]=1
myfunc() # waits for 2 seconds
REFRESH[0]=0
myfunc() # executes in no time
REFRESH[0]=1
myfunc() # waits for 2 seconds
```

This is in version 1.1.0; Please let me know if it works.

**Comment by rdooley** [comment]
Works great.
I ended up making a refresh dictionary of func_name: refresh_value which I can alter as needed.
Thanks!
